Repository dobapmin/dobapmin-frontend, pull requests merged in 2024-11, with the labels that each got.

#12 pr feat/#2-main-page-ui
  package-lock.json
  package.json
  src/assets/food_category/american.png
  src/assets/food_category/asian.png
  src/assets/food_category/chinese.png
  src/assets/food_category/dessert.png
  src/assets/food_category/diet.png
  src/assets/food_category/etc.png
  src/assets/food_category/game.png
  src/assets/food_category/japan.png
  src/assets/food_category/korean.png
  src/assets/food_category/school.png
  src/assets/pin.png
  src/assets/plus.png
  src/components/common/Layout.jsx
  src/components/main/boardCard/BoardCard.jsx
  src/components/main/boardCard/style.css
  src/components/main/boardList/BoardList.jsx
  src/components/main/boardList/style.css
  src/components/main/boardTitle/BoardTitle.jsx
  src/components/main/boardTitle/style.css
  src/components/main/postButton/PostButton.jsx
  src/components/main/postButton/style.css
  src/fonts/BMJUA_otf.otf
  src/fonts/BMJUA_ttf.ttf
  src/index.css
  src/main.jsx
  src/pages/MainPage.jsx
Labels: :sparkles: Feature, 유진

#14 pr feat/#13-fix-main-page-style
  src/index.css
Labels: :bug: Fix, 유진

#16 pr feat/#4-post-page-ui
  .prettierrc.cjs
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/Layout.jsx
  src/components/main/boardCard/BoardCard.jsx
  src/components/main/boardCard/style.css
  src/components/post/categoryBoard/CategoryButton.jsx
  src/pages/PostPage.css
  src/pages/PostPage.jsx
Labels: :sparkles: Feature, 준승

#36 pr feat/#35-animation-and-fix-design
  src/components/main/boardCard/BoardCard.jsx
  src/components/modal/DetailModal.jsx
  src/components/modal/SnackModal.jsx
  src/components/modal/index.css
Labels: :sparkles: Feature, 유진

#34 pr feat/#24-post-confirm-request
  src/lib/apis/login.js
  src/lib/apis/post.js
  src/pages/PostPage.css
  src/pages/PostPage.jsx
Labels: :twisted_rightwards_arrows: PullRequest, 준승

#38 pr resource/#37-modifying-web-page-title-and-fabicon
  index.html
  public/dobapmin_logo.png
Labels: :twisted_rightwards_arrows: PullRequest

#40 pr fix/#39-fix-participants-list
  src/components/modal/DetailModal.jsx
  src/components/modal/SnackModal.jsx
Labels: :bug: Fix, :twisted_rightwards_arrows: PullRequest, 종근

#44 pr feat/#43-update-participant-list
  src/components/main/boardCard/BoardCard.jsx
  src/components/modal/DetailModal.jsx
  src/components/modal/SnackModal.jsx
  src/pages/MainPage.jsx
Labels: :sparkles: Feature, 유진

#46 pr feat/#42-participated-button-status
  src/components/modal/DetailModal.jsx
  src/components/modal/SnackModal.jsx
Labels: :twisted_rightwards_arrows: PullRequest, 준승

#54 pr feat/#45-board-list-rendering
  src/components/modal/DetailModal.jsx
  src/components/modal/SnackModal.jsx
  src/pages/MainPage.jsx
Labels: :sparkles: Feature, 유진

#56 Feat/#55 select authority modify
  src/components/modal/DetailModal.jsx
  src/components/modal/SnackModal.jsx
Labels: :twisted_rightwards_arrows: PullRequest, :sparkles: Feature, 종근
